### ISSUE TITLE
I broke your NEI plugin

### ISSUE THREAD

**Issue by Erasmus-Crowley** [LoveHoly/Ex-Astris-2#1]
I changed the SieveRegistry and it made your NEI plugin crash. 

SieveRegistryEntry getEntryForBlockState(IBlockState state) 
is now
SieveRegistryEntry getEntryForBlockState(IBlockState state, EnumMetadataBehavior behavior)

**Comment by LlubNek** [comment]
This isn't actually fixed...  See issue #3
